addons:
  apt:
    packages:
    - libc6-i386
    
cache:
  directories:
  - /home/travis/.arduino15/
  - /usr/local/bin

before_install:
  - if ! [ "$(ls /usr/local/bin/arduino-cli)" ]; then sudo curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sudo sh; fi;
  - sudo arduino-cli core update-index --additional-urls https://github.com/Infineon/Assets/releases/download/current/package_infineon_index.json;
  - sudo arduino-cli core install Infineon:arm --additional-urls https://github.com/Infineon/Assets/releases/download/current/package_infineon_index.json
  - PACKAGE_PATH=$(ls /home/travis/.arduino15/packages/Infineon/hardware/arm/)
  - echo ${PACKAGE_PATH}
  - sudo rm /home/travis/.arduino15/packages/Infineon/hardware/arm/* -rf
  - sudo mkdir /home/travis/.arduino15/packages/Infineon/hardware/arm/${PACKAGE_PATH}
  - sudo mv ./arm/* /home/travis/.arduino15/packages/Infineon/hardware/arm/${PACKAGE_PATH}
  - ls /home/travis/.arduino15/packages/Infineon/hardware/arm/${PACKAGE_PATH}
install:
script:
  - sudo arduino-cli sketch new ci-build
  - sudo arduino-cli compile --fqbn Infineon:arm:XMC1100_Boot_Kit ci-build
  - sudo arduino-cli compile --fqbn Infineon:arm:XMC1100_XMC2GO ci-build
  - sudo arduino-cli compile --fqbn Infineon:arm:XMC1100_H_BRIDGE2GO ci-build
  - sudo arduino-cli compile --fqbn Infineon:arm:XMC1300_Boot_Kit ci-build
  - sudo arduino-cli compile --fqbn Infineon:arm:XMC1300_Sense2GoL ci-build
  - sudo arduino-cli compile --fqbn Infineon:arm:XMC4700_Radar_Baseboard ci-build
  - sudo arduino-cli compile --fqbn Infineon:arm:XMC4700_Relax_Kit ci-build
  
  
notifications:
  email:
    on_success: change
    on_failure: change