script:
- chmod +x ./scripts/trigger.sh
- "./scripts/trigger.sh"
env:
  global:
    secure: bsG2yh2beyN2QZF/kwAEJ8vZC7ns0DK19lYX+1g1XVx3eGS7HbKtXqAR6iIWiWA3rDq/F3Lz/RxLptKZ0mpa2TJ8X/OsPw1/WQxLWzaCHe0lSmlK3W+1UkqjNffnCBRL+0QBHSPTEfkrKVp+KtXxTE7Q8ZyAfhZe9ieujlzN3kMQEnN10jVqgajTJPtmUXQBFHqTcETk8OS38YiWCrH58C6so4fI8Sw5dPtOcL49otIB39HXXyDyuSMXgp0Efi6b41a96IM4v4W4e/A8tEDnRdJF4w7L6KU3SCYJkEKwq60wDEY0j6zB3+iEJaoWPIvY/eCSvmjBNGAHzi5pYT5xG1W1UTJSkbTpyZVj3bJOj/QkJvx0Y616wyoM776NllVNRghftnu2kMTV8Ip1rfgqsp/zWJoZ6YJWZNnZTPS0Gj2G3eR2eViwieZ+BxCLs4ZDTq/kHDLrq1mLFWUUhYFxhpsHUwpncMh7xMnCpmNRbQNnzQAFhknRzY+BbX/REfcjfphOtOTrNJeEPVv9WVcTwiCdQIfeTClNc7KbONZSr3luGZP1s6EJ63XesxTw18VoLj0wc7+/OcInJlUZPiweBS+p34n8ei7OabfrZLVqh+oUogns3ImT8iTCwtoeoLSnBxI/im0weE7DW+RiGCqk4AWlM9LTWFq4yPZaWyoDF5g=
